---
- name: "Appache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: Install EPEL repo
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"
    – name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
        dest: /tmp/get-pip.py
    - name: Install Python-pip
      command: python3.6 /tmp/get-pip.py
    - name: Install docker Python
      pip: name=docker-py
  tasks:
    - name: create appache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"